### ISSUE TITLE
Encountered an error while configuring the environment

### ISSUE THREAD

**Issue by Maple-sakura** [chsmiss/ATAC-amp#1]
When configuring the mamba environment, although the 'interval' module has been installed, an error 'module 'interval' has no attribute 'Interval'' occurs during runtime. I am using Python version 3.7. I infrequently use Python, and I suspect there might be a mismatch in Python or interval versions compared to the author's. Is it possible to ask you to export the analysis environment in YAML format, such as config.yaml?

**Comment by chsmiss** [comment]
Hi, thanks for your question. We have test run this on two machines with different versions of python, one with python version 3.7.12 and imported the following modules and versions:
pysam 0.21.0
networkx 2.6.3
psutil 5.9.4
interval 1.0.0
The other is using python 3.9.7 with the following dependent modules and versions.
&nbsp;psutil 5.9.0
&nbsp;networkx 3.0&nbsp;
interval 1.0.0&nbsp;
pysam 0.17.0&nbsp;
If it's not due to the version, please provide us with more detailed information about the error report and we'll be happy to fix it for you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chsmiss/ATAC-amp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 下午3:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chsmiss/ATAC-amp] Encountered an error while configuring the environment (Issue #1)





 
When configuring the mamba environment, although the 'interval' module has been installed, an error 'module 'interval' has no attribute 'Interval'' occurs during runtime. I am using Python version 3.7. I infrequently use Python, and I suspect there might be a mismatch in Python or interval versions compared to the author's. Is it possible to ask you to export the analysis environment in YAML format, such as config.yaml?

**Comment by GislaineCurty** [comment]
Hi,

Could you please provide detailed instructions on the installation process? I've encountered some errors during installation using conda environment, python 3.4 , such as with interval package:

**python AtacAmp.py -h**
Traceback (most recent call last):
  File "AtacAmp.py", line 10, in <module>
    import interval
ImportError: No module named 'interval'

conda install interval
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - interval

Current channels:

  - https://conda.anaconda.org/bioconda
  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**conda search -f interval**
Loading channels: done
No match found for: interval. Search: *interval*


Thank you!

**Comment by chsmiss** [comment]
Hi，
The interval module does not support conda installation at this time.I suggest you install it with pip intall interval，the python versions I use are 3.7 and 3.12, both are fine.Try it out and contact me if you have any questions.


Chenhansen



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 27, 2024 03:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chsmiss/ATAC-amp] Encountered an error while configuring theenvironment (Issue #1)




 
Hi,
 
Could you please provide detailed instructions on the installation process? I've encountered some errors during installation using conda environment, python 3.4 , such as with interval package:
 
python AtacAmp.py -h
 Traceback (most recent call last):
 File "AtacAmp.py", line 10, in 
 import interval
 ImportError: No module named 'interval'
 
conda install interval
 Channels:
  
bioconda
 
conda-forge
 
defaults
 Platform: linux-64
 Collecting package metadata (repodata.json): done
 Solving environment: failed
  
PackagesNotFoundError: The following packages are not available from current channels:
  
interval
  
Current channels:
  
https://conda.anaconda.org/bioconda
 
https://conda.anaconda.org/conda-forge
 
defaults
  
To search for alternate channels that may provide the conda package you're
 looking for, navigate to
 https://anaconda.org  
and use the search bar at the top of the page.
 
conda search -f interval
 Loading channels: done
 No match found for: interval. Search: interval
 
Thank you!

**Comment by chsmiss** [comment]
> Hi,
> 
> Could you please provide detailed instructions on the installation process? I've encountered some errors during installation using conda environment, python 3.4 , such as with interval package:
> 
> **python AtacAmp.py -h** Traceback (most recent call last): File "AtacAmp.py", line 10, in import interval ImportError: No module named 'interval'
> 
> conda install interval Channels:
> 
> * bioconda
> * conda-forge
> * defaults
>   Platform: linux-64
>   Collecting package metadata (repodata.json): done
>   Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * interval
> 
> Current channels:
> 
> * https://conda.anaconda.org/bioconda
> * https://conda.anaconda.org/conda-forge
> * defaults
> 
> To search for alternate channels that may provide the conda package you're looking for, navigate to
> 
> ```
> https://anaconda.org
> ```
> 
> and use the search bar at the top of the page.
> 
> **conda search -f interval** Loading channels: done No match found for: interval. Search: _interval_
> 
> Thank you!

Please try ‘pip install interval 1.0.0'
