### ISSUE TITLE
I run this useful tool and an error occurs

### ISSUE THREAD

**Issue by JiangLab-mitochondria** [chsmiss/ATAC-amp#2]
Hi,
I run this useful tool and an error occurs as follows:
Traceback (most recent call last):
  File "/ATAC-amp/AtacAmp.py", line 303, in <module>
    split_bk_dir = process_split_reads(split_bam_f)
  File "/ATAC-amp/AtacAmp.py", line 137, in process_split_reads
    breakpoint_start = split_line.pos + int(split_line.cigarstring.split('M')[0])
ValueError: invalid literal for int() with base 10: '1I102'

So how to fix it?

Thanks in advance

**Comment by chsmiss** [comment]
Thank you for your feedback, this problem is caused by the inaccurate recognition of reads with INDEL in the previous version of ATACAmp, we have made some modifications, please download the programme again and run it, if you have any problems, please feel free to contact us!

**Comment by chaiepi** [comment]
> Thank you for your feedback, this problem is caused by the inaccurate recognition of reads with INDEL in the previous version of ATACAmp, we have made some modifications, please download the programme again and run it, if you have any problems, please feel free to contact us!

Thanks for your reply. I update ATACAmp, but one more error occurs as follow:
 File "/software/ATAC-amp/AtacAmp.py", line 153
    'I').split('D')
IndentationError: unexpected indent

**Comment by chsmiss** [comment]
Sorry for leaving this error, please try again now!

**Comment by chaiepi** [comment]
Thanks for your reply. I update ATACAmp again, but another error occurs as follow:
Traceback (most recent call last):
  File "/software/ATAC-amp/AtacAmp.py", line 336, in <module>
    split_bk_dir = process_split_reads(split_bam_f)
  File "/software/ATAC-amp/AtacAmp.py", line 178, in process_split_reads
    if operation == 'I':
UnboundLocalError: local variable 'operation' referenced before assignment

**Comment by chsmiss** [comment]
Please try again, I believe the problem is now solved

**Comment by chaiepi** [comment]
No error occurs. it works!  but the output file (in my case is the file of s02.pri.atac.cancer.result) has no contents. figure as follows

![image](https://github.com/chsmiss/ATAC-amp/assets/153367180/ba273038-c5b9-422a-b1dc-539d870e7f26)

**Comment by chsmiss** [comment]
That might mean your sample doesn't have&nbsp; ecdna or hsr regions.Maybe you could try a sample that's positive for ecdna.



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 11, 2023 10:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chsmiss/ATAC-amp] I run this useful tool and an error occurs(Issue #2)




 
No error occurs. it works!  but the output file (in my case is the file of s02.pri.atac.cancer.result) has no contents. figure as follows
 
image.png (view on web)

**Comment by chaiepi** [comment]
Hello, this tool outputs this error: [E::idx_find_and_load] Could not retrieve index file for 's02.pri.atac.cancer.split.bam' . Can this error influence the final results? By the way, can you provide me a test bam file that's positive for ecdna.
